package com.xp.clothes.mapper;

import com.xp.clothes.bean.Order;
import com.xp.clothes.bean.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

@Service
public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	long countByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int deleteByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	List<Order> selectByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);
}