package com.xp.clothes.mapper;

import com.xp.clothes.bean.Userxp;
import com.xp.clothes.bean.UserxpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

@Service
public interface UserxpMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	long countByExample(UserxpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int deleteByExample(UserxpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int insert(Userxp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int insertSelective(Userxp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	List<Userxp> selectByExample(UserxpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Userxp record, @Param("example") UserxpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userxp
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	int updateByExample(@Param("record") Userxp record, @Param("example") UserxpExample example);

	int checkUser(String username);

    Userxp queryUser(@Param("user")Userxp user);
}