package com.xp.clothes.bean;

import java.util.ArrayList;
import java.util.List;

public class FactoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public FactoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFactoryidIsNull() {
			addCriterion("factoryId is null");
			return (Criteria) this;
		}

		public Criteria andFactoryidIsNotNull() {
			addCriterion("factoryId is not null");
			return (Criteria) this;
		}

		public Criteria andFactoryidEqualTo(Integer value) {
			addCriterion("factoryId =", value, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidNotEqualTo(Integer value) {
			addCriterion("factoryId <>", value, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidGreaterThan(Integer value) {
			addCriterion("factoryId >", value, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidGreaterThanOrEqualTo(Integer value) {
			addCriterion("factoryId >=", value, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidLessThan(Integer value) {
			addCriterion("factoryId <", value, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidLessThanOrEqualTo(Integer value) {
			addCriterion("factoryId <=", value, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidIn(List<Integer> values) {
			addCriterion("factoryId in", values, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidNotIn(List<Integer> values) {
			addCriterion("factoryId not in", values, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidBetween(Integer value1, Integer value2) {
			addCriterion("factoryId between", value1, value2, "factoryid");
			return (Criteria) this;
		}

		public Criteria andFactoryidNotBetween(Integer value1, Integer value2) {
			addCriterion("factoryId not between", value1, value2, "factoryid");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleIsNull() {
			addCriterion("factoryScale is null");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleIsNotNull() {
			addCriterion("factoryScale is not null");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleEqualTo(String value) {
			addCriterion("factoryScale =", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleNotEqualTo(String value) {
			addCriterion("factoryScale <>", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleGreaterThan(String value) {
			addCriterion("factoryScale >", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleGreaterThanOrEqualTo(String value) {
			addCriterion("factoryScale >=", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleLessThan(String value) {
			addCriterion("factoryScale <", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleLessThanOrEqualTo(String value) {
			addCriterion("factoryScale <=", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleLike(String value) {
			addCriterion("factoryScale like", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleNotLike(String value) {
			addCriterion("factoryScale not like", value, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleIn(List<String> values) {
			addCriterion("factoryScale in", values, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleNotIn(List<String> values) {
			addCriterion("factoryScale not in", values, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleBetween(String value1, String value2) {
			addCriterion("factoryScale between", value1, value2, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andFactoryscaleNotBetween(String value1, String value2) {
			addCriterion("factoryScale not between", value1, value2, "factoryscale");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("userName is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("userName is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("userName =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("userName <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("userName >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("userName >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("userName <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("userName <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("userName like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("userName not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("userName in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("userName not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("userName between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("userName not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andFactorynameIsNull() {
			addCriterion("factoryName is null");
			return (Criteria) this;
		}

		public Criteria andFactorynameIsNotNull() {
			addCriterion("factoryName is not null");
			return (Criteria) this;
		}

		public Criteria andFactorynameEqualTo(String value) {
			addCriterion("factoryName =", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameNotEqualTo(String value) {
			addCriterion("factoryName <>", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameGreaterThan(String value) {
			addCriterion("factoryName >", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameGreaterThanOrEqualTo(String value) {
			addCriterion("factoryName >=", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameLessThan(String value) {
			addCriterion("factoryName <", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameLessThanOrEqualTo(String value) {
			addCriterion("factoryName <=", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameLike(String value) {
			addCriterion("factoryName like", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameNotLike(String value) {
			addCriterion("factoryName not like", value, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameIn(List<String> values) {
			addCriterion("factoryName in", values, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameNotIn(List<String> values) {
			addCriterion("factoryName not in", values, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameBetween(String value1, String value2) {
			addCriterion("factoryName between", value1, value2, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorynameNotBetween(String value1, String value2) {
			addCriterion("factoryName not between", value1, value2, "factoryname");
			return (Criteria) this;
		}

		public Criteria andFactorytypeIsNull() {
			addCriterion("factoryType is null");
			return (Criteria) this;
		}

		public Criteria andFactorytypeIsNotNull() {
			addCriterion("factoryType is not null");
			return (Criteria) this;
		}

		public Criteria andFactorytypeEqualTo(String value) {
			addCriterion("factoryType =", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeNotEqualTo(String value) {
			addCriterion("factoryType <>", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeGreaterThan(String value) {
			addCriterion("factoryType >", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeGreaterThanOrEqualTo(String value) {
			addCriterion("factoryType >=", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeLessThan(String value) {
			addCriterion("factoryType <", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeLessThanOrEqualTo(String value) {
			addCriterion("factoryType <=", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeLike(String value) {
			addCriterion("factoryType like", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeNotLike(String value) {
			addCriterion("factoryType not like", value, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeIn(List<String> values) {
			addCriterion("factoryType in", values, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeNotIn(List<String> values) {
			addCriterion("factoryType not in", values, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeBetween(String value1, String value2) {
			addCriterion("factoryType between", value1, value2, "factorytype");
			return (Criteria) this;
		}

		public Criteria andFactorytypeNotBetween(String value1, String value2) {
			addCriterion("factoryType not between", value1, value2, "factorytype");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(String value) {
			addCriterion("money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(String value) {
			addCriterion("money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(String value) {
			addCriterion("money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(String value) {
			addCriterion("money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(String value) {
			addCriterion("money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(String value) {
			addCriterion("money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLike(String value) {
			addCriterion("money like", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotLike(String value) {
			addCriterion("money not like", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<String> values) {
			addCriterion("money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<String> values) {
			addCriterion("money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(String value1, String value2) {
			addCriterion("money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(String value1, String value2) {
			addCriterion("money not between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andNumberIsNull() {
			addCriterion("number is null");
			return (Criteria) this;
		}

		public Criteria andNumberIsNotNull() {
			addCriterion("number is not null");
			return (Criteria) this;
		}

		public Criteria andNumberEqualTo(String value) {
			addCriterion("number =", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotEqualTo(String value) {
			addCriterion("number <>", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThan(String value) {
			addCriterion("number >", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThanOrEqualTo(String value) {
			addCriterion("number >=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThan(String value) {
			addCriterion("number <", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThanOrEqualTo(String value) {
			addCriterion("number <=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLike(String value) {
			addCriterion("number like", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotLike(String value) {
			addCriterion("number not like", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberIn(List<String> values) {
			addCriterion("number in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotIn(List<String> values) {
			addCriterion("number not in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberBetween(String value1, String value2) {
			addCriterion("number between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotBetween(String value1, String value2) {
			addCriterion("number not between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNull() {
			addCriterion("orderType is null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNotNull() {
			addCriterion("orderType is not null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeEqualTo(String value) {
			addCriterion("orderType =", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotEqualTo(String value) {
			addCriterion("orderType <>", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThan(String value) {
			addCriterion("orderType >", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThanOrEqualTo(String value) {
			addCriterion("orderType >=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThan(String value) {
			addCriterion("orderType <", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThanOrEqualTo(String value) {
			addCriterion("orderType <=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLike(String value) {
			addCriterion("orderType like", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotLike(String value) {
			addCriterion("orderType not like", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIn(List<String> values) {
			addCriterion("orderType in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotIn(List<String> values) {
			addCriterion("orderType not in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeBetween(String value1, String value2) {
			addCriterion("orderType between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotBetween(String value1, String value2) {
			addCriterion("orderType not between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andFactorytimeIsNull() {
			addCriterion("factoryTime is null");
			return (Criteria) this;
		}

		public Criteria andFactorytimeIsNotNull() {
			addCriterion("factoryTime is not null");
			return (Criteria) this;
		}

		public Criteria andFactorytimeEqualTo(String value) {
			addCriterion("factoryTime =", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeNotEqualTo(String value) {
			addCriterion("factoryTime <>", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeGreaterThan(String value) {
			addCriterion("factoryTime >", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeGreaterThanOrEqualTo(String value) {
			addCriterion("factoryTime >=", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeLessThan(String value) {
			addCriterion("factoryTime <", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeLessThanOrEqualTo(String value) {
			addCriterion("factoryTime <=", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeLike(String value) {
			addCriterion("factoryTime like", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeNotLike(String value) {
			addCriterion("factoryTime not like", value, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeIn(List<String> values) {
			addCriterion("factoryTime in", values, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeNotIn(List<String> values) {
			addCriterion("factoryTime not in", values, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeBetween(String value1, String value2) {
			addCriterion("factoryTime between", value1, value2, "factorytime");
			return (Criteria) this;
		}

		public Criteria andFactorytimeNotBetween(String value1, String value2) {
			addCriterion("factoryTime not between", value1, value2, "factorytime");
			return (Criteria) this;
		}

		public Criteria andRegionIsNull() {
			addCriterion("region is null");
			return (Criteria) this;
		}

		public Criteria andRegionIsNotNull() {
			addCriterion("region is not null");
			return (Criteria) this;
		}

		public Criteria andRegionEqualTo(String value) {
			addCriterion("region =", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotEqualTo(String value) {
			addCriterion("region <>", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThan(String value) {
			addCriterion("region >", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThanOrEqualTo(String value) {
			addCriterion("region >=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThan(String value) {
			addCriterion("region <", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThanOrEqualTo(String value) {
			addCriterion("region <=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLike(String value) {
			addCriterion("region like", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotLike(String value) {
			addCriterion("region not like", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionIn(List<String> values) {
			addCriterion("region in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotIn(List<String> values) {
			addCriterion("region not in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionBetween(String value1, String value2) {
			addCriterion("region between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotBetween(String value1, String value2) {
			addCriterion("region not between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andFcommentsIsNull() {
			addCriterion("fComments is null");
			return (Criteria) this;
		}

		public Criteria andFcommentsIsNotNull() {
			addCriterion("fComments is not null");
			return (Criteria) this;
		}

		public Criteria andFcommentsEqualTo(String value) {
			addCriterion("fComments =", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsNotEqualTo(String value) {
			addCriterion("fComments <>", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsGreaterThan(String value) {
			addCriterion("fComments >", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsGreaterThanOrEqualTo(String value) {
			addCriterion("fComments >=", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsLessThan(String value) {
			addCriterion("fComments <", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsLessThanOrEqualTo(String value) {
			addCriterion("fComments <=", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsLike(String value) {
			addCriterion("fComments like", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsNotLike(String value) {
			addCriterion("fComments not like", value, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsIn(List<String> values) {
			addCriterion("fComments in", values, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsNotIn(List<String> values) {
			addCriterion("fComments not in", values, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsBetween(String value1, String value2) {
			addCriterion("fComments between", value1, value2, "fcomments");
			return (Criteria) this;
		}

		public Criteria andFcommentsNotBetween(String value1, String value2) {
			addCriterion("fComments not between", value1, value2, "fcomments");
			return (Criteria) this;
		}

		public Criteria andPictureIsNull() {
			addCriterion("picture is null");
			return (Criteria) this;
		}

		public Criteria andPictureIsNotNull() {
			addCriterion("picture is not null");
			return (Criteria) this;
		}

		public Criteria andPictureEqualTo(String value) {
			addCriterion("picture =", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotEqualTo(String value) {
			addCriterion("picture <>", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureGreaterThan(String value) {
			addCriterion("picture >", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureGreaterThanOrEqualTo(String value) {
			addCriterion("picture >=", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLessThan(String value) {
			addCriterion("picture <", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLessThanOrEqualTo(String value) {
			addCriterion("picture <=", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLike(String value) {
			addCriterion("picture like", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotLike(String value) {
			addCriterion("picture not like", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureIn(List<String> values) {
			addCriterion("picture in", values, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotIn(List<String> values) {
			addCriterion("picture not in", values, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureBetween(String value1, String value2) {
			addCriterion("picture between", value1, value2, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotBetween(String value1, String value2) {
			addCriterion("picture not between", value1, value2, "picture");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table factory
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table factory
     *
     * @mbg.generated do_not_delete_during_merge Sat May 25 16:05:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}