package com.xp.clothes.bean;

public class Factory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factory_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.user_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factory_type1
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String factoryType1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.user_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.pnumber
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer pnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factory_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.ft_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String ftType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.money
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.fs_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer fsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.order_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.chothes_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String chothesType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.region
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.site
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.f_comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String fComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.picture
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factory_id
     *
     * @return the value of factory.factory_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factory_id
     *
     * @param factoryId the value for factory.factory_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.user_id
     *
     * @return the value of factory.user_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.user_id
     *
     * @param userId the value for factory.user_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factory_type1
     *
     * @return the value of factory.factory_type1
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getFactoryType1() {
        return factoryType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factory_type1
     *
     * @param factoryType1 the value for factory.factory_type1
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setFactoryType1(String factoryType1) {
        this.factoryType1 = factoryType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.user_name
     *
     * @return the value of factory.user_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.user_name
     *
     * @param userName the value for factory.user_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.pnumber
     *
     * @return the value of factory.pnumber
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.pnumber
     *
     * @param pnumber the value for factory.pnumber
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setPnumber(Integer pnumber) {
        this.pnumber = pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factory_name
     *
     * @return the value of factory.factory_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factory_name
     *
     * @param factoryName the value for factory.factory_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.ft_type
     *
     * @return the value of factory.ft_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getFtType() {
        return ftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.ft_type
     *
     * @param ftType the value for factory.ft_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setFtType(String ftType) {
        this.ftType = ftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.money
     *
     * @return the value of factory.money
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.money
     *
     * @param money the value for factory.money
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.fs_id
     *
     * @return the value of factory.fs_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getFsId() {
        return fsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.fs_id
     *
     * @param fsId the value for factory.fs_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setFsId(Integer fsId) {
        this.fsId = fsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.order_type
     *
     * @return the value of factory.order_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.order_type
     *
     * @param orderType the value for factory.order_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.chothes_type
     *
     * @return the value of factory.chothes_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getChothesType() {
        return chothesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.chothes_type
     *
     * @param chothesType the value for factory.chothes_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setChothesType(String chothesType) {
        this.chothesType = chothesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.region
     *
     * @return the value of factory.region
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.region
     *
     * @param region the value for factory.region
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.site
     *
     * @return the value of factory.site
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.site
     *
     * @param site the value for factory.site
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setSite(String site) {
        this.site = site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.f_comments
     *
     * @return the value of factory.f_comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getfComments() {
        return fComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.f_comments
     *
     * @param fComments the value for factory.f_comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setfComments(String fComments) {
        this.fComments = fComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.picture
     *
     * @return the value of factory.picture
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.picture
     *
     * @param picture the value for factory.picture
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }
}