package com.xp.clothes.bean;

public class FactoryScale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_scale. id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_scale.comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_scale. id
     *
     * @return the value of factory_scale. id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_scale. id
     *
     * @param id the value for factory_scale. id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_scale.comments
     *
     * @return the value of factory_scale.comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_scale.comments
     *
     * @param comments the value for factory_scale.comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}