package com.xp.clothes.bean;

public class Factory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.factoryId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private Integer factoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.factoryScale
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String factoryscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.factoryName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String factoryname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.factoryType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String factorytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.money
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.number
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.orderType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String ordertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.factoryTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String factorytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.region
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.address
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.fComments
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String fcomments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factory.status
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.factoryId
	 * @return  the value of factory.factoryId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Integer getFactoryid() {
		return factoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.factoryId
	 * @param factoryid  the value for factory.factoryId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setFactoryid(Integer factoryid) {
		this.factoryid = factoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.userId
	 * @return  the value of factory.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.userId
	 * @param userid  the value for factory.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.factoryScale
	 * @return  the value of factory.factoryScale
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getFactoryscale() {
		return factoryscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.factoryScale
	 * @param factoryscale  the value for factory.factoryScale
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setFactoryscale(String factoryscale) {
		this.factoryscale = factoryscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.userName
	 * @return  the value of factory.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.userName
	 * @param username  the value for factory.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.phone
	 * @return  the value of factory.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.phone
	 * @param phone  the value for factory.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.factoryName
	 * @return  the value of factory.factoryName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getFactoryname() {
		return factoryname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.factoryName
	 * @param factoryname  the value for factory.factoryName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setFactoryname(String factoryname) {
		this.factoryname = factoryname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.factoryType
	 * @return  the value of factory.factoryType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getFactorytype() {
		return factorytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.factoryType
	 * @param factorytype  the value for factory.factoryType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setFactorytype(String factorytype) {
		this.factorytype = factorytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.money
	 * @return  the value of factory.money
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.money
	 * @param money  the value for factory.money
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.number
	 * @return  the value of factory.number
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.number
	 * @param number  the value for factory.number
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setNumber(String number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.orderType
	 * @return  the value of factory.orderType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getOrdertype() {
		return ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.orderType
	 * @param ordertype  the value for factory.orderType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setOrdertype(String ordertype) {
		this.ordertype = ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.factoryTime
	 * @return  the value of factory.factoryTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getFactorytime() {
		return factorytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.factoryTime
	 * @param factorytime  the value for factory.factoryTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setFactorytime(String factorytime) {
		this.factorytime = factorytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.region
	 * @return  the value of factory.region
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.region
	 * @param region  the value for factory.region
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.address
	 * @return  the value of factory.address
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.address
	 * @param address  the value for factory.address
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.fComments
	 * @return  the value of factory.fComments
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getFcomments() {
		return fcomments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.fComments
	 * @param fcomments  the value for factory.fComments
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setFcomments(String fcomments) {
		this.fcomments = fcomments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.picture
	 * @return  the value of factory.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.picture
	 * @param picture  the value for factory.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factory.status
	 * @return  the value of factory.status
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factory.status
	 * @param status  the value for factory.status
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}