package com.xp.clothes.bean;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pnumber
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String pnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.count
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.product_class
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String productClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.comeondate
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Date comeondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.comeoffdate
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private Date comeoffdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.region
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.size
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String oComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.picture
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_name
     *
     * @return the value of order.user_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_name
     *
     * @param userName the value for order.user_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pnumber
     *
     * @return the value of order.pnumber
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pnumber
     *
     * @param pnumber the value for order.pnumber
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setPnumber(String pnumber) {
        this.pnumber = pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_name
     *
     * @return the value of order.order_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_name
     *
     * @param orderName the value for order.order_name
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.count
     *
     * @return the value of order.count
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.count
     *
     * @param count the value for order.count
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.product_class
     *
     * @return the value of order.product_class
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.product_class
     *
     * @param productClass the value for order.product_class
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setProductClass(String productClass) {
        this.productClass = productClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.comeondate
     *
     * @return the value of order.comeondate
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Date getComeondate() {
        return comeondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.comeondate
     *
     * @param comeondate the value for order.comeondate
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setComeondate(Date comeondate) {
        this.comeondate = comeondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.comeoffdate
     *
     * @return the value of order.comeoffdate
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public Date getComeoffdate() {
        return comeoffdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.comeoffdate
     *
     * @param comeoffdate the value for order.comeoffdate
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setComeoffdate(Date comeoffdate) {
        this.comeoffdate = comeoffdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.region
     *
     * @return the value of order.region
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.region
     *
     * @param region the value for order.region
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.size
     *
     * @return the value of order.size
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.size
     *
     * @param size the value for order.size
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_comments
     *
     * @return the value of order.o_comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getoComments() {
        return oComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_comments
     *
     * @param oComments the value for order.o_comments
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setoComments(String oComments) {
        this.oComments = oComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.picture
     *
     * @return the value of order.picture
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.picture
     *
     * @param picture the value for order.picture
     *
     * @mbg.generated Thu May 23 18:04:41 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }
}