package com.xp.clothes.bean;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private Integer orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String ordername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.count
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.price
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.cloth
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String cloth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String ordertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.endTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String ordertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.region
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.address
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.comments
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String comments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.status
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderId
	 * @return  the value of order.orderId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderId
	 * @param orderid  the value for order.orderId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.userId
	 * @return  the value of order.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.userId
	 * @param userid  the value for order.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.userName
	 * @return  the value of order.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.userName
	 * @param username  the value for order.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.phone
	 * @return  the value of order.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.phone
	 * @param phone  the value for order.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderName
	 * @return  the value of order.orderName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getOrdername() {
		return ordername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderName
	 * @param ordername  the value for order.orderName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setOrdername(String ordername) {
		this.ordername = ordername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.count
	 * @return  the value of order.count
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.count
	 * @param count  the value for order.count
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setCount(String count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.price
	 * @return  the value of order.price
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.price
	 * @param price  the value for order.price
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.cloth
	 * @return  the value of order.cloth
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getCloth() {
		return cloth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.cloth
	 * @param cloth  the value for order.cloth
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setCloth(String cloth) {
		this.cloth = cloth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderTime
	 * @return  the value of order.orderTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getOrdertime() {
		return ordertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderTime
	 * @param ordertime  the value for order.orderTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setOrdertime(String ordertime) {
		this.ordertime = ordertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.endTime
	 * @return  the value of order.endTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.endTime
	 * @param endtime  the value for order.endTime
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderType
	 * @return  the value of order.orderType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getOrdertype() {
		return ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderType
	 * @param ordertype  the value for order.orderType
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setOrdertype(String ordertype) {
		this.ordertype = ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.region
	 * @return  the value of order.region
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.region
	 * @param region  the value for order.region
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.address
	 * @return  the value of order.address
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.address
	 * @param address  the value for order.address
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.comments
	 * @return  the value of order.comments
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.comments
	 * @param comments  the value for order.comments
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.picture
	 * @return  the value of order.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.picture
	 * @param picture  the value for order.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.status
	 * @return  the value of order.status
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.status
	 * @param status  the value for order.status
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}