package com.xp.clothes.bean;

public class Userxp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userxp.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userxp.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userxp.password
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userxp.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userxp.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	private String picture;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userxp.userId
	 * @return  the value of userxp.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userxp.userId
	 * @param userid  the value for userxp.userId
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userxp.phone
	 * @return  the value of userxp.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userxp.phone
	 * @param phone  the value for userxp.phone
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userxp.password
	 * @return  the value of userxp.password
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userxp.password
	 * @param password  the value for userxp.password
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userxp.userName
	 * @return  the value of userxp.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userxp.userName
	 * @param username  the value for userxp.userName
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userxp.picture
	 * @return  the value of userxp.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userxp.picture
	 * @param picture  the value for userxp.picture
	 * @mbg.generated  Sat May 25 22:51:14 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}
}