package com.xp.clothes.bean;

public class Userxp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userxp.user_id
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userxp.pn
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    private Integer pn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userxp.password
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userxp.username
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userxp.picture
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userxp.user_id
     *
     * @return the value of userxp.user_id
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userxp.user_id
     *
     * @param userId the value for userxp.user_id
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userxp.pn
     *
     * @return the value of userxp.pn
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public Integer getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userxp.pn
     *
     * @param pn the value for userxp.pn
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public void setPn(Integer pn) {
        this.pn = pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userxp.password
     *
     * @return the value of userxp.password
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userxp.password
     *
     * @param password the value for userxp.password
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userxp.username
     *
     * @return the value of userxp.username
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userxp.username
     *
     * @param username the value for userxp.username
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userxp.picture
     *
     * @return the value of userxp.picture
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userxp.picture
     *
     * @param picture the value for userxp.picture
     *
     * @mbg.generated Fri May 24 19:29:20 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }
}